- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
It's good practice, especially with NodeJS projects, to sandbox them from the rest of the system they're running on. Docker is a good way to do this.
> Add Docker Compose setup for production use

- src/components/dropdown.js
- src/components/map.js
A collection of fixes for minor problems I'm finding.
- Fix runtime warning.
- Use JS localization methods instead of rolling our own.
> Minor fixes

- src/components/map.js
- src/css/map.css
> Show names of SA2s on mouseover and selection

- .gitignore
- package-lock.json
- package.json
- src/components/display.js
- src/components/map.js
- src/components/segregation.js
added tooltips to legend, hover details on map, added zoom on segregation map, removed "click SA to view details about it" modal that was showing after clicking on an area
> tooltips and zoom issue fixed

- public/index.html
- src/components/map.js
- src/css/map.css
Buttons for zooming the map in and out.
See [this Figma mockup for review](https://www.figma.com/file/vP3gxGjxW34i5gNMpu6sDW/Design-V1?node-id=160%3A637).
> Zoom buttons

- package-lock.json
- src/components/header.js
- src/css/header.css
Header has been redone according to [this Figma](https://www.figma.com/file/vP3gxGjxW34i5gNMpu6sDW/Design-V1?node-id=1113%3A77).
Also ported over a lot of the inline css on the header into its own css file.
Fixes #55
> New Header

- src/App.js
- src/components/header.js
- src/components/legend.js
- src/components/map.js
- src/components/searchbar.js
- src/css/header.css
- src/data/README.md
- src/pages/main.js
- src/redux/reducer.js
Basic prep for the new UI design:
- Doesn't show a modal dialog on start
- Starts the map zoomed to fit South Australia
- Moves search to top left
- Moves legend to bottom left
- Makes the header transparent and ignore clicks
Also fixes some bugs introduced by the latest GeoJSON file.
> Reposition view components

- src/components/LocationDetails.js
- src/css/collapsible.css
- src/utils/formatValue.js
> Add inline comparison for each metric

- src/components/propsMapping.js
- src/data/anzsic_codes.json
- src/utils/formatValue.js
- Add more data to the main SA_dashboard.geojson file.
- Update propsMapping with placeholder names and formats for things that should get displayed to end users.
- Add a separate ANZSIC code list for use elsewhere.
> Add more data [WIP]

- src/components/ModalContainer.js
- src/components/RecommendationDialog.js
- src/components/WelcomeDialog.js
- src/css/ModalContainer.css
- src/css/footer.css
- src/css/header.css
- src/css/recommendation.css
- src/pages/about.js
- src/pages/faq.js
- src/pages/main.js
- src/pages/methods.js
- src/pages/research.js
Various minor content and styling changes.
> Miscellaneous tweaks

- src/components/LocationDetails.js
- src/components/TableView.js
- src/components/charts/LineChartMetric.js
- src/css/TableView.css
- src/css/collapsible.css
> No data in linechart

- src/components/LocationDetails.js
- src/components/Sidebar.js
- src/css/Sidebar.css
> Update Sidebar to include first collapsible in the scrolling div

- src/css/GridView.css
- src/css/TableView.css
- src/css/main.css
- src/pages/main.js
> Make whole comparison view scrollable

- src/components/GridView.js
- src/components/LocationDetails.js
- src/css/collapsible.css
> Show a "No data" row for sections without metrics

- src/components/legend.js
> Legend gradient

- src/components/GridView.js
- src/components/TableView.js
- src/css/GridView.css
> Comparison collapsible redux

- package-lock.json
- package.json
- src/components/RecommendationTool.js
- src/components/TypeaheadSelect.js
- src/constants.js
- src/css/recommendation.css
- src/pages/recommendation.js
- src/redux/getters.js
A typeahead search field is necessary for the ANZSIC code / business type question in the recommendation tool.
Resolves #149.
> Add typeahead component and simple recommendation algorithm

- frontend/mocked_api_responses/detail_data_example_small_business_support_adelaide.json
- frontend/mocked_api_responses/detail_layout_description.md
- frontend/mocked_api_responses/detail_layout_example_small_business_support.json
Also includes an example of a single region's data response
To be used for developing visualizations while backend is built.
> Add a first pass at mocking a layout response

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ChartFlyOut/ChartFlyOut.js
- frontend/src/components/SectionStackedArea/SectionStackedArea.js
- frontend/src/components/SectionStackedArea/index.js
- frontend/src/components/StackChart/StackChart.js
- frontend/src/components/StackChart/StackChart.stories.js
- frontend/src/components/StackChart/StackChart.utils.js
- frontend/src/components/StackChart/index.js
- frontend/src/mocked_api_responses/detail_layout_example_small_business_support.json
- frontend/src/routes/SmallBusinessSupport/SmallBusinessSupport.js
> SA-192 stack chart

- frontend/src/components/ExpandableContainer/ExpandableContainer.js
- frontend/src/components/ExpandableContainer/ExpandableContainer.stories.js
- frontend/src/components/ExpandableContainer/index.js
- frontend/src/components/SectionSimpleBar/SectionSimpleBar.js
- frontend/src/components/SectionSimpleRange/SectionSimpleRange.js
- frontend/src/components/SectionText/SectionText.js
- frontend/src/utils/constants.js
> SA-192 Implement show more/less feature with ExpandableContainer

- frontend/src/components/LineChart/LineChart.js
- frontend/src/components/MetricsContainer/MetricsContainer.js
- frontend/src/components/MetricsContainer/MetricsContainer.utils.js
- frontend/src/components/MetricsContainer/index.js
- frontend/src/components/StackChart/StackChart.js
- frontend/src/mocked_api_responses/detail_layout_example_small_business_support.json
- frontend/src/routes/SmallBusinessSupport/SmallBusinessSupport.js
> SA-192 Re-implement columns layout with MetricsContainer

- frontend/src/components/ExpandableContainer/ExpandableContainer.js
- frontend/src/components/ExpandableContainer/ExpandableContainer.stories.js
- frontend/src/components/ExpandableContainer/ExpandableContainer.utils.js
- frontend/src/components/FilterSelect/FilterSelect.js
- frontend/src/components/FilterSelect/FilterSelect.stories.js
- frontend/src/components/FilterSelect/FilterSelect.utils.js
- frontend/src/components/FilterSelect/index.js
- frontend/src/components/MetricFilters/MetricFilters.js
- frontend/src/components/MetricFilters/MetricFilters.stories.js
- frontend/src/components/MetricFilters/index.js
- frontend/src/components/SectionText/SectionText.js
- frontend/src/utils/propTypes.js
> SA-192 Implement select filter

- frontend/src/components/Map/Map.js
- frontend/src/utils/constants.js
Not consider popup idle when map is moving,
Hide map popup when cursor is away,
Expand map popup on feature click
> Popup enhancements: #209

- frontend/src/components/Map/Map.js
> Remove unnecessary createStyles call in Map.js

- frontend/src/components/Map/Map.js
> Track map position in URL hash

- frontend/src/components/Map/Map.js
- frontend/src/components/MapPopupContent/MapPopupContent.js
- frontend/src/routes/Dataset/Dataset.js
- frontend/src/utils/theme.js
> Add map popup link to selected feature

- frontend/src/components/MapPopupContent/MapPopupContent.js
- frontend/src/routes/Home/Home.js
- frontend/src/utils/theme.js
> Make MUI links use react-router Link component

- frontend/src/components/ExpandableContainer/ExpandableContainer.js
> Make DatasetEntry page "Show more" links bold

- frontend/src/components/Header/SearchInput.js
- frontend/src/components/Map/Map.js
- frontend/src/routes/Dataset/Dataset.js
- frontend/src/store/modules/api/call.js
- frontend/src/store/modules/index.js
- frontend/src/store/modules/sagas.js
- frontend/src/store/modules/search/actions.js
- frontend/src/store/modules/search/index.js
- frontend/src/store/modules/search/reducers.js
- frontend/src/store/modules/search/sagas.js
- frontend/src/store/modules/search/selectors.js
- frontend/src/store/modules/search/types.js
- frontend/src/utils/theme.js
> Sa 232 search functionality

- backend/api/views.py
Was raising an exception whenever the Mapbox Geocoding API didn't return any results
> Fix regression in search endpoint

- frontend/src/components/Map/Map.js
> Add map feature highlight for search options

- frontend/src/components/Header/SearchInput.js
- frontend/src/components/Map/Map.js
> Make map popup disappear when search input is cleared

- frontend/src/components/ExpandableContainer/ExpandableContainer.utils.js
> Fix filtering utilizer

- backend/api/fixtures/initial.json
- backend/api/views.py
Add Mean Income, Median Income, and Income Quartile chloropleths to Small Business Support dataset.
> Add more metrics to exploreLayout in initial.json

- frontend/src/components/Map/Map.js
- frontend/src/components/SimpleRange/SimpleRange.js
- frontend/src/routes/Dataset/Dataset.js
Update map cleanup logic,
Update SimpleRange component gradient generation function,
Resolves #272
> Make map metric select work,

- frontend/src/components/LineChart/LineChart.js
- frontend/src/components/StackChart/StackChart.js
- frontend/src/utils/victory.js
> Make chart labels to support date formatters

- frontend/src/components/LineChart/LineChart.js
- frontend/src/components/StackChart/StackChart.js
- frontend/src/utils/victory.js
> Enhance charts to support angled label

- frontend/src/components/Map/Map.js
> Fix map zoom performance on multiple metric changes: fix onMapMove function event listener removing

- frontend/src/components/ComparisonMenu/ComparisonMenu.js
- frontend/src/routes/DatasetCompare/DatasetCompare.js
- frontend/src/routes/Home/Home.js
- frontend/src/routes/SmallBusinessSupport/SmallBusinessSupport.js
- frontend/src/store/modules/dataset/sagas.js
- frontend/src/utils/path.js
You can see the comparison page
-through the home page(I alreday set up the 4 entries: 405031120, 406021140, 401011001, 404031105)
-by clicking "View Comparison" button if you added entries in compare menu
> Show differences of selected entries(cities for small-business-support) in the comparison page.
